using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Food.Property
{
    public partial class Form_Add_Property : DevExpress.XtraEditors.XtraForm
    {
        BL.Property.Property property = new BL.Property.Property();
        Form_Properties form_property = null;

        public Form_Add_Property()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        public void setObject(Form_Properties form_property)
        {
            this.form_property = form_property;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                property.add_property(txtName.Text, txtName.Text, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();
                sqlDataSource1.FillAsync();

                if (this.form_property != null)
                    this.form_property.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}