using DevExpress.Data;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Order
{
    public partial class Form_Order_Histories : DevExpress.XtraEditors.XtraForm
    {
        BL.Pos.Pos pos = new BL.Pos.Pos();
        string whichOne = "";
        bool FromPos = false;

        public Form_Order_Histories()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceClients.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceSattled.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceSubmitted.FillAsync();
        }

        public void setWhichOne(string whichOne)
        {
            this.whichOne = whichOne;
        }
        public void setFromPos(bool FromPos)
        {
            this.FromPos = FromPos;
        }

        private void txtClient_EditValueChanged(object sender, EventArgs e)
        {
            gridControlSettled.DataSource = pos.get_food_orders_by_client(Convert.ToInt32(txtClient.EditValue));
            gridControlSubmitted.DataSource = pos.get_food_orders_by_client(Convert.ToInt32(txtClient.EditValue));
        }

        private void textPeriodeDate_EditValueChanged(object sender, EventArgs e)
        {
            if (textPeriodeDate.EditValue.ToString() == "All")
            {
                gridViewISubmitted.ActiveFilterString = null;
                gridViewSettled.ActiveFilterString = null;
            }
            else if (textPeriodeDate.EditValue.ToString() == "To Day")
            {
                gridViewISubmitted.ActiveFilterString = string.Format("IsOutlookIntervalToday([created_at])");
                gridViewSettled.ActiveFilterString = string.Format("IsOutlookIntervalToday([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "This Week")
            {
                gridViewISubmitted.ActiveFilterString = string.Format("IsThisWeek([created_at])");
                gridViewSettled.ActiveFilterString = string.Format("IsThisWeek([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "Last Week")
            {
                gridViewISubmitted.ActiveFilterString = string.Format("IsOutlookIntervalLastWeek([created_at])");
                gridViewSettled.ActiveFilterString = string.Format("IsOutlookIntervalLastWeek([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "Newest")
            {
                gridViewISubmitted.Columns["id"].SortOrder = ColumnSortOrder.Ascending;
                gridViewSettled.Columns["id"].SortOrder = ColumnSortOrder.Ascending;
            }
            else if (textPeriodeDate.EditValue.ToString() == "Oldest")
            {
                gridViewISubmitted.Columns["id"].SortOrder = ColumnSortOrder.Descending;
                gridViewSettled.Columns["id"].SortOrder = ColumnSortOrder.Descending;
            }
            else if (textPeriodeDate.EditValue.ToString() == "Between the dates")
            {
                startDate.Enabled = true;
                endDate.Enabled = true;
                gridViewISubmitted.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
                gridViewSettled.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
            }
        }

        private void startDate_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void endDate_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void btnPos_Click(object sender, EventArgs e)
        {
            if (this.FromPos)
            {
                this.Close();
            }
            else
            {
                PL.Pos.Form_Pos pos = new PL.Pos.Form_Pos();
                pos.ShowDialog();
            }
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            textPeriodeDate.EditValue = "";
            startDate.Text = DateTime.Now.ToString();
            endDate.Text = DateTime.Now.ToString();

            if (Properties.Settings.Default.sound == "yes")
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Wrong.wav");
                simpleSound.Play();
            }
        }

        private void Form_Order_Histories_Load(object sender, EventArgs e)
        {
            if (this.whichOne == "Settled")
            {
                this.tabbedControlGroup1.SelectedTabPage = this.layoutControlGroup1;
            }
        }
    }
}