using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Restaurant.PaymentType
{
    public partial class Form_Add_Payment_Type : DevExpress.XtraEditors.XtraForm
    {
        BL.PaymentType.PaymentType payment_type = new BL.PaymentType.PaymentType();
        Form_Payment_Type form_payment_type = null;

        public Form_Add_Payment_Type()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourcePaymentType.FillAsync();
        }

        public void setObject(Form_Payment_Type form_payment_type)
        {
            this.form_payment_type = form_payment_type;
        }

        private void btnAdd_Click_1(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                DataTable tb = payment_type.exists(txtKey.Text);

                if( tb.Rows.Count == 0 )
                {
                    payment_type.add_payment_type(txtName.Text, txtName.Text, txtKey.Text, DateTime.Now, DateTime.Now);
                    txtName.Clear();
                    txtName.Select();

                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                        simpleSound.Play();
                    }
                } else
                {
                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                        simpleSound.Play();
                    }
                    MessageBox.Show("Input key exists déja");
                }

                sqlDataSourcePaymentType.FillAsync();

                if (this.form_payment_type != null)
                    this.form_payment_type.asyncData();
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}