using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Restaurant.PaymentType
{
    public partial class Form_Edit_Payment_Type : DevExpress.XtraEditors.XtraForm
    {
        BL.PaymentType.PaymentType payment_type = new BL.PaymentType.PaymentType();
        Form_Payment_Type form_payment_type = null;
        int payment_type_id = 0;
        string old_input_key = "";

        public Form_Edit_Payment_Type()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourcePaymentType.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = payment_type.get_payment_type(this.payment_type_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
                txtKey.Text = tb.Rows[0]["input_key"].ToString();
                this.old_input_key = tb.Rows[0]["input_key"].ToString();
            }
        }

        public void setObject(Form_Payment_Type form_payment_type)
        {
            this.form_payment_type = form_payment_type;
        }

        public void setID(int payment_type_id)
        {
            this.payment_type_id = payment_type_id;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                DataTable tb = payment_type.exists(txtKey.Text);

                if (txtKey.Text == this.old_input_key)
                {
                    payment_type.update_payment_type(this.payment_type_id, txtName.Text, txtName.Text, txtKey.Text, DateTime.Now);
                    txtName.Select();
                    sqlDataSourcePaymentType.FillAsync();

                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                        simpleSound.Play();
                    }
                } else {
                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                        simpleSound.Play();
                    }
                    MessageBox.Show("Input key exists déja");
                }

                if (this.form_payment_type != null)
                    this.form_payment_type.asyncData();
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Payment_Type_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}