using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Food.Property
{
    public partial class Form_Edit_Property : DevExpress.XtraEditors.XtraForm
    {
        BL.Property.Property property = new BL.Property.Property();
        Form_Properties form_properties = null;
        int property_id = 0;

        public Form_Edit_Property()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceProperty.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = property.get_property(this.property_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
            }
        }

        public void setObject(Form_Properties form_properties)
        {
            this.form_properties = form_properties;
        }

        public void setID(int property_id)
        {
            this.property_id = property_id;
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                property.update_property(this.property_id, txtName.Text, txtName.Text, DateTime.Now);
                txtName.Select();
                sqlDataSourceProperty.FillAsync();

                if (this.form_properties != null)
                    this.form_properties.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Property_Load(object sender, EventArgs e)
        {
            loadData();
        }

        private void btnAddPropItems_Click(object sender, EventArgs e)
        {
            PropertyItems.Form_Property_Items_List item = new PropertyItems.Form_Property_Items_List();
            item.ShowDialog();
        }
    }
}