using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Credit
{
    public partial class Form_Add_Credit : DevExpress.XtraEditors.XtraForm
    {
        BL.Credit.Credit credit = new BL.Credit.Credit();
        int supp_id = 0;
        bool canClose = false;

        public Form_Add_Credit()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceSupplier.FillAsync();
        }

        private void btnNewCustomer_Click(object sender, EventArgs e)
        {
            Stock.Supplier.Form_Add_Supplier supplier = new Stock.Supplier.Form_Add_Supplier();
            supplier.ShowDialog();
        }

        private void gridViewSupplier_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            object value = this.gridViewSupplier.GetRowCellValue(this.gridViewSupplier.FocusedRowHandle, "id");
            this.supp_id = Convert.ToInt32(value);
            txtClient.Text = this.gridViewSupplier.GetRowCellValue(this.gridViewSupplier.FocusedRowHandle, "name").ToString();

        }

        private void btnSave_Click(object sender, EventArgs e)
        {

            if (dxValidationProvider1.Validate())
            {
                credit.InsertCredit(this.supp_id, txtTypeCredit.EditValue.ToString(), txtEtat.Text, Convert.ToDecimal(txtMontant.Text), txtMethode.EditValue.ToString(), txtDate.DateTime, txtNote.Text);
                //sqlDataSource1.FillAsync();
                txtClient.Clear();
                txtClient.Select();

                if(Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                    this.canClose = true;
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void btnSaveExit_Click(object sender, EventArgs e)
        {
            btnSave.PerformClick();
            if (this.canClose)
                this.Close();
        }
    }
}