using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Credit
{
    public partial class Form_Add_Versement : DevExpress.XtraEditors.XtraForm
    {
        public static Form_Add_Versement instance;
        BL.Credit.Versemenet versemenet = new BL.Credit.Versemenet();
        BL.Credit.Credit credit = new BL.Credit.Credit();
        DataTable tb;
        int supp_id = 0;
        int credit_id = 0;
        bool canClose = false;

        public Form_Add_Versement()
        {
            InitializeComponent();
            instance = this;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceSupplier.FillAsync();
        }

        public void setCreditID(int credit_id)
        {
            this.credit_id = credit_id;
        }
        public void setSuppID(int supp_id)
        {
            this.supp_id = supp_id;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                versemenet.InsertVeresement(Convert.ToDecimal(txtMontant.Text), txtDate.DateTime, this.credit_id, txtNote.Text.ToString());
                txtSupplier.Clear();
                txtSupplier.Select();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }

                this.canClose = true;
                Form_Credit.instance.intanciateVersementTab();
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void btnAddExit_Click(object sender, EventArgs e)
        {
            btnAdd.PerformClick();
            if (this.canClose)
                this.Close();
        }

        private void txtClient_EditValueChanged(object sender, EventArgs e)
        {
            DataTable tb = credit.get_credit(this.credit_id);
            if (tb.Rows.Count > 0)
            {
                txtMontantRest.Text = tb.Rows[0][0].ToString();
                txtMontantRestAdd.Text = tb.Rows[0][0].ToString();
                txtPayee.Text = tb.Rows[0][0].ToString();
                txtPayeeAdd.Text = tb.Rows[0][0].ToString();
                txtMontantCredit.Text = tb.Rows[0]["Montant"].ToString();
                txtRemarqueCredit.Text = tb.Rows[0]["Notes"].ToString();
            }
        }

        private void Form_Add_Versement_Load(object sender, EventArgs e)
        {
            txtDate.DateTime = DateTime.Now;
            txtSupplier.EditValue = this.supp_id;
            txtMontantRest.Text = "0";
            txtMontant.Text = "0";

            if (this.credit_id != 0)
            {
                tb = credit.get_credit(this.credit_id);
                if (tb.Rows.Count > 0)
                {
                    string remaining_amount = credit.get_remaining_amount(this.credit_id);

                    if (string.IsNullOrEmpty(remaining_amount))
                    {
                        remaining_amount = "0";
                        txtMontantRestAdd.Text = remaining_amount;
                    }
                    else
                    {
                        txtMontantRestAdd.Text = (
                            (Convert.ToDecimal(tb.Rows[0]["Montant"]) - Convert.ToDecimal(remaining_amount)) >= 0
                            ? (Convert.ToDecimal(tb.Rows[0]["Montant"]) - Convert.ToDecimal(remaining_amount))
                            : 0
                            ).ToString();
                    }

                    txtMontantRest.Text = (
                        (Convert.ToDecimal(tb.Rows[0]["Montant"]) - Convert.ToDecimal(remaining_amount)) >= 0
                        ? (Convert.ToDecimal(tb.Rows[0]["Montant"]) - Convert.ToDecimal(remaining_amount))
                        : 0
                        ).ToString();


                    txtPayee.Text = remaining_amount;
                    txtPayeeAdd.Text = remaining_amount; //change
                    txtMontantCredit.Text = tb.Rows[0]["Montant"].ToString();
                    txtRemarqueCredit.Text = tb.Rows[0]["Notes"].ToString();
                }
            }
        }

        private void txtMontant_EditValueChanged(object sender, EventArgs e)
        {
            txtMontantRestAdd.Text = (
               Convert.ToDecimal(txtMontantRest.Text) - Convert.ToDecimal(txtMontant.Text) >= 0
               ? Convert.ToDecimal(txtMontantRest.Text) - Convert.ToDecimal(txtMontant.Text)
               : 0
               ).ToString();
            txtPayeeAdd.Text = Convert.ToDecimal(txtMontant.Text).ToString();
        }
    }
}