using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Food.Variation
{
    public partial class Form_Add_Variation : DevExpress.XtraEditors.XtraForm
    {
        BL.Variation.Variation variation = new BL.Variation.Variation();
        Form_Variations form_Variation = null;

        public Form_Add_Variation()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        public void setObject(Form_Variations form_Variation)
        {
            this.form_Variation = form_Variation;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {

            if (dxValidationProvider1.Validate())
            {
                variation.add_variation(txtName.Text, txtName.Text, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();
                sqlDataSource1.FillAsync();

                if( this.form_Variation != null )
                    this.form_Variation.asyncData();
                
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Add_Variation_Load(object sender, EventArgs e)
        {

        }
    }
}