using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Food.Variation
{
    public partial class Form_Edit_Variation : DevExpress.XtraEditors.XtraForm
    {
        BL.Variation.Variation variation = new BL.Variation.Variation();
        Form_Variations form_Variation = null;
        int variation_id = 0;

        public Form_Edit_Variation()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = variation.get_variation(this.variation_id);
            if( tb.Rows.Count > 0 )
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
            }
        }

        public void setObject(Form_Variations form_Variation)
        {
            this.form_Variation = form_Variation;
        }

        public void setID(int variation_id)
        {
            this.variation_id = variation_id;
        }
        
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                variation.update_variation(this.variation_id,txtName.Text, txtName.Text, DateTime.Now);
                txtName.Select();
                sqlDataSource1.FillAsync();

                if (this.form_Variation != null)
                    this.form_Variation.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Variation_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}