using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Credit
{
    public partial class Form_Credit : DevExpress.XtraEditors.XtraForm
    {
        BL.Credit.Versemenet versemenet = new BL.Credit.Versemenet();
        BL.Credit.Credit credit = new BL.Credit.Credit();
        public static Form_Credit instance;
        int supp_id = 0;

        public Form_Credit()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceSupplier.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceCreditUnPaid.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceCreditPaid.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceCreditUnPaid.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceVersement.FillAsync();

            instance = this;
        }

        public void setSuppID(int supp_id)
        {
            this.supp_id = supp_id;
        }

        public void intanciateVersementTab()
        {
            sqlDataSourceVersement.FillAsync();

        }

        private void btnNewSupplier_Click(object sender, EventArgs e)
        {
            Stock.Supplier.Form_Add_Supplier supplier = new Stock.Supplier.Form_Add_Supplier();
            supplier.ShowDialog();
        }

        private void btnNewCredit_Click_1(object sender, EventArgs e)
        {
            Form_Add_Credit credit = new Form_Add_Credit();
            credit.ShowDialog();
        }

        private void btnNewVersement_Click_1(object sender, EventArgs e)
        {
            Form_Add_Versement versement = new Form_Add_Versement();
            versement.ShowDialog();
        }

        private void gridControlCreditUnPaid_DoubleClick_1(object sender, EventArgs e)
        {
            object CreditID = this.gridViewCreditUnPaid.GetRowCellValue(this.gridViewCreditUnPaid.FocusedRowHandle, "Credit_ID");
            object SuppID = this.gridViewCreditUnPaid.GetRowCellValue(this.gridViewCreditUnPaid.FocusedRowHandle, "id");
            Form_Add_Versement versement = new Form_Add_Versement();
            versement.setCreditID(Convert.ToInt32(CreditID));
            versement.setSuppID(Convert.ToInt32(SuppID));
            versement.ShowDialog();
        }

        private void gridViewCreditUnPaid_RowClick_1(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            object CreditID = this.gridViewCreditUnPaid.GetRowCellValue(this.gridViewCreditUnPaid.FocusedRowHandle, "Credit_ID");

            gridControlVersement.DataSource = versemenet.get_veresement_by_credit_id(Convert.ToInt32(CreditID));
        }

        private void Form_Credit_Load(object sender, EventArgs e)
        {
            if (this.supp_id != 0)
                txtSupplierID.EditValue = this.supp_id;
        }

        private void txtSupplierID_EditValueChanged(object sender, EventArgs e)
        {
            if (this.supp_id != 0)
            {
                gridControlCreditUnPaid.DataSource = credit.get_credit_by_cust_id(this.supp_id, "Non Payée");
                gridControlCreditPaid.DataSource = credit.get_credit_by_cust_id(this.supp_id, "Payée");
            }
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            if (Properties.Settings.Default.sound == "yes")
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Deleted.wav");
                simpleSound.Play();
            }
        }
    }
}