using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Restaurant.Branch
{
    public partial class Form_Add_Branch : DevExpress.XtraEditors.XtraForm
    {
        BL.Branch.Branch branch = new BL.Branch.Branch();
        Form_Branch_List form_branch_list = null;
        string active = "Inactive";

        public Form_Add_Branch()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceBranch.FillAsync();
        }

        public void setObject(Form_Branch_List form_branch_list)
        {
            this.form_branch_list = form_branch_list;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                branch.add_branch(txtName.Text, txtDeleveryFree.Text, txtName.Text,txtAdress.Text, textPhone.Text, "SaaS Banner", "Saas Thumb", this.active, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();
                sqlDataSourceBranch.FillAsync();

                if (this.form_branch_list != null)
                    this.form_branch_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void checkEditActive_CheckedChanged(object sender, EventArgs e)
        {
            this.active = "Inactive";
            if (checkEditActive.Checked)
                this.active = "Active";
        }
    }
}