using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Stock.Supplier
{
    public partial class Form_Add_Supplier : DevExpress.XtraEditors.XtraForm
    {
        BL.Supplier.Supplier supplier = new BL.Supplier.Supplier();
        Form_Supplier_List form_supplier_list = null;

        public Form_Add_Supplier()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSourceSupplier.Fill();
        }

        public void setObject(Form_Supplier_List form_supplier_list)
        {
            this.form_supplier_list = form_supplier_list;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                supplier.add_supplier(txtName.Text, txtName.Text, txtEmail.Text, txtPhone.Text, 0, txtAddress.Text, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();

                sqlDataSourceSupplier.FillAsync();

                if (this.form_supplier_list != null)
                    this.form_supplier_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}