using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Food.FoodGroup
{
    public partial class Form_Edit_Food_Group : DevExpress.XtraEditors.XtraForm
    {
        BL.FoodGroup.FoodGroup food_group = new BL.FoodGroup.FoodGroup();
        Form_Food_Group form_food_group = null;
        int food_group_id = 0;

        public Form_Edit_Food_Group()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceFoodGroup.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = food_group.get_food_group(this.food_group_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
            }
        }

        public void setObject(Form_Food_Group form_food_group)
        {
            this.form_food_group = form_food_group;
        }

        public void setID(int food_group_id)
        {
            this.food_group_id = food_group_id;
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                food_group.update_food_group(this.food_group_id, txtName.Text, txtName.Text, DateTime.Now);
                txtName.Select();
                sqlDataSourceFoodGroup.FillAsync();

                if (this.form_food_group != null)
                    this.form_food_group.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Food_Group_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}