using DevExpress.Data;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Stock.IngredientItem
{
    public partial class Form_Ingredient_Item : DevExpress.XtraEditors.XtraForm
    {
        BL.IngredientItem.IngredientItem ingredient_item = new BL.IngredientItem.IngredientItem();
        int ingredient_item_id = 0;
        bool filter = true;

        public Form_Ingredient_Item()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceIngredientItem.FillAsync();
        }

        public void asyncData()
        {
            sqlDataSourceIngredientItem.FillAsync();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            Form_Add_Ingredient_Item form_ingredient_item = new Form_Add_Ingredient_Item();
            form_ingredient_item.setObject(this);
            form_ingredient_item.ShowDialog();
        }

        private void gridViewIngredientItem_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            object value = this.gridViewIngredientItem.GetRowCellValue(this.gridViewIngredientItem.FocusedRowHandle, "id");
            this.ingredient_item_id = Convert.ToInt32(value);
            btnEdit.Enabled = true;
            btnDelete.Enabled = true;
        }

        private void gridControlIngredientItem_DoubleClick(object sender, EventArgs e)
        {
            object value = this.gridViewIngredientItem.GetRowCellValue(this.gridViewIngredientItem.FocusedRowHandle, "id");
            Form_Edit_Ingredient_Item form_ingredient_item = new Form_Edit_Ingredient_Item();
            form_ingredient_item.setID(Convert.ToInt32(value));
            form_ingredient_item.setObject(this);
            form_ingredient_item.ShowDialog();
        }

        private void btnEdit_Click(object sender, EventArgs e)
        {
            if (this.ingredient_item_id != 0)
            {
                Form_Edit_Ingredient_Item form_ingredient_item = new Form_Edit_Ingredient_Item();
                form_ingredient_item.setID(this.ingredient_item_id);
                form_ingredient_item.setObject(this);
                form_ingredient_item.ShowDialog();
            }
        }

        private void Form_Ingredient_Item_Load(object sender, EventArgs e)
        {
            btnEdit.Enabled = false;
            btnDelete.Enabled = false;
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            if (this.ingredient_item_id != 0)
            {
                DialogResult dialogResult = MessageBox.Show("Are You Sure,You Whant Delete This Item ?", "Delete This Item", MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    ingredient_item.delete(this.ingredient_item_id);
                    this.asyncData();
                    btnEdit.Enabled = false;
                    btnDelete.Enabled = false;
                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\Deleted.wav");
                        simpleSound.Play();
                    }
                }
                else if (dialogResult == DialogResult.No)
                {
                    // do something
                }
            }
        }

        private void textPeriodeDate_EditValueChanged(object sender, EventArgs e)
        {
            if (textPeriodeDate.EditValue.ToString() == "All")
            {
                gridViewIngredientItem.ActiveFilterString = null;
            }
            else if (textPeriodeDate.EditValue.ToString() == "To Day")
            {
                gridViewIngredientItem.ActiveFilterString = string.Format("IsOutlookIntervalToday([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "This Week")
            {
                gridViewIngredientItem.ActiveFilterString = string.Format("IsThisWeek([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "Last Week")
            {
                gridViewIngredientItem.ActiveFilterString = string.Format("IsOutlookIntervalLastWeek([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "Newest")
            {
                gridViewIngredientItem.Columns["id"].SortOrder = ColumnSortOrder.Ascending;
            }
            else if (textPeriodeDate.EditValue.ToString() == "Oldest")
            {
                gridViewIngredientItem.Columns["id"].SortOrder = ColumnSortOrder.Descending;
            }
            else if (textPeriodeDate.EditValue.ToString() == "Between the dates")
            {
                startDate.Enabled = true;
                endDate.Enabled = true;
                gridViewIngredientItem.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
            }
        }

        private void btnReset_Click(object sender, EventArgs e)
        {
            gridViewIngredientItem.ActiveFilterString = null;
            this.filter = false;
            gridViewIngredientItem.ClearSorting();
            gridViewIngredientItem.ApplyFindFilter(string.Empty);
            textPeriodeDate.EditValue = "";
            startDate.Text = DateTime.Now.ToString();
            endDate.Text = DateTime.Now.ToString();
            if (Properties.Settings.Default.sound == "yes")
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                simpleSound.Play();
            }
        }

        private void startDate_EditValueChanged(object sender, EventArgs e)
        {
            if (endDate.EditValue != null & this.filter)
                gridViewIngredientItem.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
        }

        private void endDate_EditValueChanged(object sender, EventArgs e)
        {
            if (startDate.EditValue != null & this.filter)
                gridViewIngredientItem.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
        }
    }
}