using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Stock.IngredientItem
{
    public partial class Form_Add_Ingredient_Item : DevExpress.XtraEditors.XtraForm
    {
        BL.IngredientItem.IngredientItem ingredient_item = new BL.IngredientItem.IngredientItem();
        Form_Ingredient_Item form_ingredient_item = null;

        public Form_Add_Ingredient_Item()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceIngredientItem.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceIngredientGroup.FillAsync();
        }

        public void setObject(Form_Ingredient_Item form_ingredient_item)
        {
            this.form_ingredient_item = form_ingredient_item;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                ingredient_item.add_ingredient_item(Convert.ToInt32(txtIngGroup.EditValue),txtName.Text, txtName.Text, txtName.Text,txtUnite.Text, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();

                sqlDataSourceIngredientItem.FillAsync();

                if (this.form_ingredient_item != null)
                    this.form_ingredient_item.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}