using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.User.PermissionGroup
{
    public partial class Form_Permissions : DevExpress.XtraEditors.XtraForm
    {
        BL.PermissionGroup.PermissionGroup permission_group = new BL.PermissionGroup.PermissionGroup();
        Form_Permissions_Group form_permission = null;
        int permission_group_id = 0;

        public Form_Permissions()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            this.load();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourcePermissions.FillAsync();
        }

        public void setObject(Form_Permissions_Group form_permission)
        {
            this.form_permission = form_permission;
        }

        public void setID(int permission_group_id)
        {
            this.permission_group_id = permission_group_id;
        }

        public void setGroupName(string groupName)
        {
            //Group.Text = groupName;
        }
        
        private void Form_Permissions_Load(object sender, EventArgs e)
        {
            this.load();
        }

        public void load()
        {
            gridControlGpHasPermissions.DataSource = permission_group.get_all_group_permissions(this.permission_group_id);
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                permission_group.add_permission_to_group( Convert.ToInt32(txtPermission.EditValue), this.permission_group_id, DateTime.Now, DateTime.Now);
                txtPermission.Clear();
                txtPermission.Select();

                this.load();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void repositoryItemButtonEditDelete_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            object value = this.gridViewGpHasPermissions.GetRowCellValue(this.gridViewGpHasPermissions.FocusedRowHandle, "id");
            permission_group.delete_permission_from_group(Convert.ToInt32(value));
            this.load();
        }
    }
}