using DevExpress.Data;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.User.PermissionGroup
{
    public partial class Form_Permissions_Group : DevExpress.XtraEditors.XtraForm
    {
        BL.PermissionGroup.PermissionGroup permission_group = new BL.PermissionGroup.PermissionGroup();
        int permission_group_id = 0;
        bool filter = true;

        public Form_Permissions_Group()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourcePermissionGroup.FillAsync();
        }

        public void asyncData()
        {
            sqlDataSourcePermissionGroup.FillAsync();
        }

        private void btnAdd_Click_1(object sender, EventArgs e)
        {
            Form_Add_Permission_Group permission = new Form_Add_Permission_Group();
            permission.setObject(this);
            permission.ShowDialog();
        }

        private void gridViewProperty_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            object value = this.gridViewPermissionGroup.GetRowCellValue(this.gridViewPermissionGroup.FocusedRowHandle, "id");
            this.permission_group_id = Convert.ToInt32(value);
            btnEdit.Enabled = true;
            btnDelete.Enabled = true;
        }

        private void gridControlProperty_DoubleClick(object sender, EventArgs e)
        {
            object value = this.gridViewPermissionGroup.GetRowCellValue(this.gridViewPermissionGroup.FocusedRowHandle, "id");
            Form_Edit_Permission_Group permission = new Form_Edit_Permission_Group();
            permission.setID(Convert.ToInt32(value));
            permission.setObject(this);
            permission.ShowDialog();
        }

        private void btnEdit_Click_1(object sender, EventArgs e)
        {
            if (this.permission_group_id != 0)
            {
                Form_Edit_Permission_Group permission = new Form_Edit_Permission_Group();
                permission.setID(this.permission_group_id);
                permission.setObject(this);
                permission.ShowDialog();
            }
        }

        private void Form_Properties_Load(object sender, EventArgs e)
        {
            btnEdit.Enabled = false;
            btnDelete.Enabled = false;
        }

        private void btnDelete_Click_1(object sender, EventArgs e)
        {
            if (this.permission_group_id != 0)
            {
                DialogResult dialogResult = MessageBox.Show("Are You Sure,You Whant Delete This Item ?", "Delete This Item", MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    permission_group.delete(this.permission_group_id);
                    this.asyncData();
                    btnEdit.Enabled = false;
                    btnDelete.Enabled = false;
                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\Deleted.wav");
                        simpleSound.Play();
                    }
                }
                else if (dialogResult == DialogResult.No)
                {
                    // do something
                }
            }
        }

        private void textPeriodeDate_EditValueChanged_1(object sender, EventArgs e)
        {
            if (textPeriodeDate.EditValue.ToString() == "All")
            {
                gridViewPermissionGroup.ActiveFilterString = null;
            }
            else if (textPeriodeDate.EditValue.ToString() == "To Day")
            {
                gridViewPermissionGroup.ActiveFilterString = string.Format("IsOutlookIntervalToday([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "This Week")
            {
                gridViewPermissionGroup.ActiveFilterString = string.Format("IsThisWeek([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "Last Week")
            {
                gridViewPermissionGroup.ActiveFilterString = string.Format("IsOutlookIntervalLastWeek([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "Newest")
            {
                gridViewPermissionGroup.Columns["id"].SortOrder = ColumnSortOrder.Ascending;
            }
            else if (textPeriodeDate.EditValue.ToString() == "Oldest")
            {
                gridViewPermissionGroup.Columns["id"].SortOrder = ColumnSortOrder.Descending;
            }
            else if (textPeriodeDate.EditValue.ToString() == "Between the dates")
            {
                startDate.Enabled = true;
                endDate.Enabled = true;
                gridViewPermissionGroup.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
            }
        }

        private void btnReset_Click_1(object sender, EventArgs e)
        {
            this.filter = false;
            gridViewPermissionGroup.ClearSorting();
            gridViewPermissionGroup.ApplyFindFilter(string.Empty);
            textPeriodeDate.EditValue = "";
            startDate.Text = DateTime.Now.ToString();
            endDate.Text = DateTime.Now.ToString();
            if (Properties.Settings.Default.sound == "yes")
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Wrong.wav");
                simpleSound.Play();
            }
        }

        private void startDate_EditValueChanged_1(object sender, EventArgs e)
        {
            if ( endDate.EditValue != null & this.filter )
                gridViewPermissionGroup.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
        }

        private void endDate_EditValueChanged_1(object sender, EventArgs e)
        {
            if ( startDate.EditValue != null & this.filter )
                gridViewPermissionGroup.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
        }

        private void reposiButtonEditPermmission_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            object value = this.gridViewPermissionGroup.GetRowCellValue(this.gridViewPermissionGroup.FocusedRowHandle, "id");
        }

        private void reposiButtonEditPermmission_Click(object sender, EventArgs e)
        {
            object value = this.gridViewPermissionGroup.GetRowCellValue(this.gridViewPermissionGroup.FocusedRowHandle, "id");
            object group = this.gridViewPermissionGroup.GetRowCellValue(this.gridViewPermissionGroup.FocusedRowHandle, "name");
            Form_Permissions permissions = new Form_Permissions();
            permissions.setID(Convert.ToInt32(value));
            permissions.setGroupName(group.ToString());
            permissions.setObject(this);
            permissions.ShowDialog();
        }
    }
}