using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Restaurant.DepartmentTagList
{
    public partial class Form_Add_Department_Tag : DevExpress.XtraEditors.XtraForm
    {
        BL.DepartmentTagList.DepartmentTagList department_tag_list = new BL.DepartmentTagList.DepartmentTagList();
        Form_Department_Tag_List form_department_tag_list = null;

        public Form_Add_Department_Tag()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceDepartmentTagList.FillAsync();
        }

        public void setObject(Form_Department_Tag_List form_department_tag_list)
        {
            this.form_department_tag_list = form_department_tag_list;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                department_tag_list.add_department_tag_list(txtName.Text, txtName.Text, txtCommission.Text, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();
                sqlDataSourceDepartmentTagList.FillAsync();

                if (this.form_department_tag_list != null)
                    this.form_department_tag_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}