using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Stock.IngredientGroup
{
    public partial class Form_Edit_Ingredient_Group : DevExpress.XtraEditors.XtraForm
    {
        BL.IngredientGroup.IngredientGroup ingredient_group = new BL.IngredientGroup.IngredientGroup();
        Form_Ingredient_Group form_ingredient_group = null;
        int ingredient_group_id = 0;

        public Form_Edit_Ingredient_Group()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceIngredientGroup.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = ingredient_group.get_ingredient_group(this.ingredient_group_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
            }
        }

        public void setObject(Form_Ingredient_Group form_ingredient_group)
        {
            this.form_ingredient_group = form_ingredient_group;
        }

        public void setID(int ingredient_group_id)
        {
            this.ingredient_group_id = ingredient_group_id;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                ingredient_group.update_ingredient_group(this.ingredient_group_id, txtName.Text, txtName.Text, DateTime.Now);
                txtName.Select();
                sqlDataSourceIngredientGroup.FillAsync();

                if (this.form_ingredient_group != null)
                    this.form_ingredient_group.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Ingredient_Group_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}