using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Settings.Language
{
    public partial class Form_Edit_Language : DevExpress.XtraEditors.XtraForm
    {
        BL.Language.Language language = new BL.Language.Language();
        Form_Language_List form_language_list = null;
        int language_id = 0;

        public Form_Edit_Language()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceLanguage.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = language.get_language(this.language_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
                txtCode.Text = tb.Rows[0]["code"].ToString();
                langImage.EditValue = tb.Rows[0]["image"];
            }
        }

        public void setObject(Form_Language_List form_language_list)
        {
            this.form_language_list = form_language_list;
        }

        public void setID(int language_id)
        {
            this.language_id = language_id;
        }

        private void btnSave_Click_1(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                byte[] bytes;
                MemoryStream stream = new MemoryStream();
                langImage.Image.Save(stream, ImageFormat.Jpeg);
                bytes = stream.ToArray();

                language.update_language(this.language_id,txtName.Text, bytes, 0, txtCode.Text, DateTime.Now);
                
                txtName.Select();

                sqlDataSourceLanguage.FillAsync();

                if (this.form_language_list != null)
                    this.form_language_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Language_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}