using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Settings.Language
{
    public partial class Form_Add_Language : DevExpress.XtraEditors.XtraForm
    {
        BL.Language.Language language = new BL.Language.Language();
        Form_Language_List form_language_list = null;

        public Form_Add_Language()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceLanguage.FillAsync();
        }

        public void setObject(Form_Language_List form_language_list)
        {
            this.form_language_list = form_language_list;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                byte[] bytes;
                MemoryStream stream = new MemoryStream();
                langImage.Image.Save(stream, ImageFormat.Jpeg);
                bytes = stream.ToArray();

                language.add_language(txtName.Text, bytes,0, txtCode.Text, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();
                sqlDataSourceLanguage.FillAsync();

                if (this.form_language_list != null)
                    this.form_language_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}