using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.User.Permission
{
    public partial class Form_Edit_Permission : DevExpress.XtraEditors.XtraForm
    {
        BL.Permission.Permission permission = new BL.Permission.Permission();
        Form_Permissions form_permission = null;
        int permission_id = 0;

        public Form_Edit_Permission()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourcePermission.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = permission.get_permission(this.permission_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
            }
        }

        public void setObject(Form_Permissions form_permission)
        {
            this.form_permission = form_permission;
        }

        public void setID(int permission_id)
        {
            this.permission_id = permission_id;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                permission.update_permission(this.permission_id, txtName.Text, txtName.Text, DateTime.Now);
                txtName.Select();
                sqlDataSourcePermission.FillAsync();

                if (this.form_permission != null)
                    this.form_permission.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Permission_Load_1(object sender, EventArgs e)
        {
            loadData();
        }
    }
}