using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.User.Permission
{
    public partial class Form_Add_Permission : DevExpress.XtraEditors.XtraForm
    {
        BL.Permission.Permission permission = new BL.Permission.Permission();
        Form_Permissions form_permission = null;

        public Form_Add_Permission()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourcePermission.FillAsync();
        }

        public void setObject(Form_Permissions form_permission)
        {
            this.form_permission = form_permission;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                permission.add_permission(txtName.Text, txtName.Text, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();
                sqlDataSourcePermission.FillAsync();

                if (this.form_permission != null)
                    this.form_permission.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}