using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Customer
{
    public partial class Form_customer_points : DevExpress.XtraEditors.XtraForm
    {
        BL.Customer.Customer customer = new BL.Customer.Customer();
        Pos.Form_Pos form_pos = new Pos.Form_Pos();
        int customer_id = 0;

        public Form_customer_points()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSourceCustomer.Fill();
        }

        public void setObject(Pos.Form_Pos form_pos)
        {
            this.form_pos = form_pos;
        }

        public void setID(int customer_id)
        {
            this.customer_id = customer_id;
        }

        private void txtName_EditValueChanged(object sender, EventArgs e)
        {
            if(txtName.EditValue != null)
            {
                this.customer_id = Convert.ToInt32(txtName.EditValue);
                DataTable dt = customer.get_customer(this.customer_id);

                if (dt.Rows.Count > 0)
                {
                    txtPoints.Text = dt.Rows[0]["points"].ToString();
                    txtTotal.Text = (Convert.ToDecimal(Properties.Settings.Default.pointMoney) * Convert.ToInt32(dt.Rows[0]["points"].ToString())).ToString();
                }
            }
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (txtName.EditValue != null && txtPoints.EditValue != null)
            {
                customer.update_customer_points(this.customer_id, txtPoints.Text, DateTime.Now);

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                    MessageBox.Show("Please select Custmoer");
                }
            }
        }

        private void Form_customer_points_Load(object sender, EventArgs e)
        {
            // do something...
        }
    }
}