using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Settings.Currency
{
    public partial class Form_Add_Currency : DevExpress.XtraEditors.XtraForm
    {
        BL.Currency.Currency currency = new BL.Currency.Currency();
        Form_Currency_List form_currency_list = null;

        public Form_Add_Currency()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceCurrency.FillAsync();
        }

        public void setObject(Form_Currency_List form_currency_list)
        {
            this.form_currency_list = form_currency_list;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {

            if (dxValidationProvider1.Validate())
            {
                currency.add_currency(txtName.Text, txtSymbol.Text,Convert.ToDecimal(txtRate.Text),txtAllignment.Text,0,txtCode.Text, DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();
                sqlDataSourceCurrency.FillAsync();

                if (this.form_currency_list != null)
                    this.form_currency_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}