using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Auth
{
    public partial class Form_Login : DevExpress.XtraEditors.XtraForm
    {
        BL.Setting.Setting setting = new BL.Setting.Setting();
        BL.Auth.Auth login = new BL.Auth.Auth();
        BL.Currency.Currency currency = new BL.Currency.Currency();
        int setting_id = 30;

        public Form_Login()
        {
            Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo(Properties.Settings.Default.lang);
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSourceBranch.Fill();
        }

        private void Form_Login_Load(object sender, EventArgs e)
        {

        }

        private void btnLogin_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                DataTable dt = login.login(txtUserName.Text, txtPassword.Text);
                DataTable cr = currency.get_currency();

                if (dt.Rows.Count > 0)
                {
                    Properties.Settings.Default.userID = Convert.ToInt32(dt.Rows[0]["id"]);
                    Properties.Settings.Default.userName = dt.Rows[0]["name"].ToString();
                    Properties.Settings.Default.branchId = Convert.ToInt32(branch.EditValue);
                    Properties.Settings.Default.branchName = branch.Text;
                    Properties.Settings.Default.restaurantId = Convert.ToInt32(dt.Rows[0]["restaurant_id"]);
                    Properties.Settings.Default.currency = cr.Rows[0]["symbol"].ToString();
                    
                    DataTable tb = setting.get_setting_by_id(this.setting_id);

                    if (tb.Rows.Count > 0)
                    {
                        Properties.Settings.Default.pointMoney = tb.Rows[0]["point_money"].ToString();
                        Properties.Settings.Default.sound = tb.Rows[0]["sound"].ToString();
                    }

                    Form_Home home = new Form_Home();
                    home.ShowDialog();
                    this.Close();

                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                        simpleSound.Play();
                    }
                }
                else
                {

                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                        simpleSound.Play();
                    }
                    MessageBox.Show("Username or Password is incorrect");
                }
            }
            else
            {

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            txtUserName.Clear();
            txtPassword.Clear();

            if (Properties.Settings.Default.sound == "yes")
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Wrong.wav");
                simpleSound.Play();
            }
        }
    }
}