using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.User.Waiter
{
    public partial class Form_Waiter : DevExpress.XtraEditors.XtraForm
    {
        BL.Waiter.Waiter waiter = new BL.Waiter.Waiter();
        DataTable tb, waiters = new DataTable();
        Form_Waiters_List form_waiters_list;
        int waiter_id = 0;
        int max_id = 0;
        int row;

        public Form_Waiter()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceWaiter.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceBranch.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceWaiter.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceWaiter.FillAsync();
        }

        public void setObject(Form_Waiters_List form_waiters_list)
        {
            this.form_waiters_list = form_waiters_list;
        }

        public void setID(int waiter_id)
        {
            this.waiter_id = waiter_id;
            this.row = waiter_id;
        }

        public void last_id()
        {
            txtID.Text = (Convert.ToInt32(waiter.get_last_id())+1).ToString();
            this.max_id = Convert.ToInt32(waiter.get_last_id());

            txtName.Clear();
            txtNotes.Clear();
            txtPhone.Clear();
            memoAdress.Clear();
            pictureEditWaiter.EditValue = null;

            btnAdd.Enabled = true;
            btnRefresh.Enabled = true;
            btnDelete.Enabled = false;
            btnDeleteAll.Enabled = false;
            btnSave.Enabled = false;
        }

        public void load()
        {
            //DataTable tb = waiter.get_waiter(Convert.ToInt32(txtID.Text));

            if (this.waiters.Rows.Count <= row)
            {
                MessageBox.Show("Aucune donnée sur cet écran");
            }
            else
            {
                txtID.Text = this.waiters.Rows[row]["id"].ToString();
                txtName.Text = this.waiters.Rows[row]["name"].ToString();
                memoAdress.Text = this.waiters.Rows[row]["address"].ToString();
                txtPhone.Text = this.waiters.Rows[row]["phn_no"].ToString();
                txtBranch.EditValue = this.waiters.Rows[row]["branch_id"];
                pictureEditWaiter.EditValue = this.waiters.Rows[row]["image"];

                btnAdd.Enabled = false;
                btnRefresh.Enabled = true;
                btnDelete.Enabled = true;
                btnDeleteAll.Enabled = true;
                btnSave.Enabled = true;
            }

        }

        public void Get(int id)
        {
            DataTable tb = waiter.get_waiter(id);

            if (tb.Rows.Count <= 0)
            {
                MessageBox.Show("Aucune donnée sur cet écran");
            }
            else
            {
                txtID.Text = tb.Rows[0]["id"].ToString();
                txtName.Text = tb.Rows[0]["name"].ToString();
                memoAdress.Text = tb.Rows[0]["address"].ToString();
                txtPhone.Text = tb.Rows[0]["phn_no"].ToString();
                txtBranch.EditValue = tb.Rows[0]["branch_id"];
                pictureEditWaiter.EditValue = tb.Rows[0]["image"];

                btnAdd.Enabled = false;
                btnRefresh.Enabled = true;
                btnDelete.Enabled = true;
                btnDeleteAll.Enabled = true;
                btnSave.Enabled = true;
            }

        }

        private void Form_Add_Waiter_Load(object sender, EventArgs e)
        {
            this.waiters = waiter.get_all_waiters();
            if ( this.waiter_id != 0 )
            {
                txtID.Text = this.waiter_id.ToString();
                this.Get(this.waiter_id);
            } else
            {
                // TODO: This line of code loads data into the 'customerDataSet.Customers' table. You can move, or remove it, as needed.
                //this.customersTableAdapter.Fill(this.customerDataSet.Customers);
                last_id();

                if (waiter.get_last_id() == "")
                {
                    txtID.Text = "1";
                    btnRight.Enabled = false;
                    btnRight2.Enabled = false;
                    btnLeft.Enabled = false;
                    btnLeft2.Enabled = false;
                } else
                {
                    this.row = Convert.ToInt32(waiter.get_last_id());
                }
            }
            

        }

        private void textEdit5_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton7_Click(object sender, EventArgs e)
        {

        }

        private void textEdit5_EditValueChanged_1(object sender, EventArgs e)
        {

        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            last_id();
        }

        private void txtPohne_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                byte[] bytes;
                MemoryStream stream = new MemoryStream();
                pictureEditWaiter.Image.Save(stream, ImageFormat.Jpeg);
                bytes = stream.ToArray();
                waiter.add_waiter(txtName.Text,txtPhone.Text, txtName.Text, memoAdress.Text, bytes, Convert.ToInt32(txtBranch.EditValue),DateTime.Now,DateTime.Now);
                
                this.last_id();

                if (this.form_waiters_list != null)
                    this.form_waiters_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                byte[] bytes;
                MemoryStream stream = new MemoryStream();
                pictureEditWaiter.Image.Save(stream, ImageFormat.Jpeg);
                bytes = stream.ToArray();

                waiter.update_waiter(Convert.ToInt32(txtID.Text),txtName.Text, txtPhone.Text, txtName.Text, memoAdress.Text, bytes, Convert.ToInt32(txtBranch.EditValue), DateTime.Now);

                if (this.form_waiters_list != null)
                    this.form_waiters_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void btnDeleteAll_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("êtes-vous sûr ?", "Confirmer", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                waiter.delete_all();
                this.last_id();
            }
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("êtes-vous sûr ?", "Confirmer", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                waiter.delete(Convert.ToInt32(txtID.Text));
                this.last_id();
            }
        }

        private void btnRight2_Click(object sender, EventArgs e)
        {
            row = Convert.ToInt32(waiter.get_last_id()) - 1;
            load();
            btnRight.Enabled = false;
            btnLeft.Enabled = true;
        }

        private void btnRight_Click(object sender, EventArgs e)
        {
            if ((Convert.ToInt32(waiter.get_last_id())) > row)
            {
                row++;
                load();
                btnLeft.Enabled = true;
            }
            else
            {
                btnRight.Enabled = false;
            }
        }

        private void btnLeft2_Click(object sender, EventArgs e)
        {
            row = 0;
            load();
            btnLeft.Enabled = false;
            btnRight.Enabled = true;
        }

        private void btnLeft_Click(object sender, EventArgs e)
        {
            if (row > 0)
            {
                row--;
                load();
                btnRight.Enabled = true;
            }
            else
            {
                btnLeft.Enabled = false;
            }
        }

        private void searchLookUpClient_EditValueChanged(object sender, EventArgs e)
        {
            object obj = searchLookUpWaiter.EditValue;
            //string text = searchLookUpClient.Text;
            //MessageBox.Show(obj.ToString());
            Get(Convert.ToInt32(obj));
        }

        private void searchLookUpClient_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
        }

        private void searchLookUpClient_ButtonPressed(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            MessageBox.Show(e.ToString());
        }

        private void btnExit_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}