using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Food.Unit
{
    public partial class Form_Edit_Unit : DevExpress.XtraEditors.XtraForm
    {
        BL.Unit.Unit unit = new BL.Unit.Unit();
        Form_Units form_units = null;
        int unit_id = 0;

        public Form_Edit_Unit()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceUnit.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = unit.get_unit(this.unit_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
            }
        }

        public void setObject(Form_Units form_units)
        {
            this.form_units = form_units;
        }

        public void setID(int unit_id)
        {
            this.unit_id = unit_id;
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                unit.update_unit(this.unit_id, txtName.Text, txtName.Text, DateTime.Now);
                txtName.Select();
                sqlDataSourceUnit.FillAsync();

                if (this.form_units != null)
                    this.form_units.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Unit_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}