using DevExpress.Data;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Food.Unit
{
    public partial class Form_Units : DevExpress.XtraEditors.XtraForm
    {
        BL.Unit.Unit unit = new BL.Unit.Unit();
        int unit_id = 0;
        bool filter = true;

        public Form_Units()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceUnit.FillAsync();
        }

        public void asyncData()
        {
            sqlDataSourceUnit.FillAsync();
        }

        private void btnAdd_Click_1(object sender, EventArgs e)
        {
            Form_Add_Unit unit = new Form_Add_Unit();
            unit.setObject(this);
            unit.ShowDialog();
        }

        private void gridViewProperty_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            object value = this.gridViewUnit.GetRowCellValue(this.gridViewUnit.FocusedRowHandle, "id");
            this.unit_id = Convert.ToInt32(value);
            btnEdit.Enabled = true;
            btnDelete.Enabled = true;
        }

        private void gridControlProperty_DoubleClick(object sender, EventArgs e)
        {
            object value = this.gridViewUnit.GetRowCellValue(this.gridViewUnit.FocusedRowHandle, "id");
            Form_Edit_Unit unit = new Form_Edit_Unit();
            unit.setID(Convert.ToInt32(value));
            unit.setObject(this);
            unit.ShowDialog();
        }

        private void btnEdit_Click_1(object sender, EventArgs e)
        {
            if (this.unit_id != 0)
            {
                Form_Edit_Unit unit = new Form_Edit_Unit();
                unit.setID(this.unit_id);
                unit.setObject(this);
                unit.ShowDialog();
            }
        }

        private void Form_Properties_Load(object sender, EventArgs e)
        {
            btnEdit.Enabled = false;
            btnDelete.Enabled = false;
        }

        private void btnDelete_Click_1(object sender, EventArgs e)
        {
            if (this.unit_id != 0)
            {
                DialogResult dialogResult = MessageBox.Show("Are You Sure,You Whant Delete This Item ?", "Delete This Item", MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    unit.delete(this.unit_id);
                    this.asyncData();
                    btnEdit.Enabled = false;
                    btnDelete.Enabled = false;

                    if (Properties.Settings.Default.sound == "yes")
                    {
                        SoundPlayer simpleSound = new SoundPlayer(@"c:\Deleted.wav");
                        simpleSound.Play();
                    }
                }
                else if (dialogResult == DialogResult.No)
                {
                    // do something
                }
            }
        }

        private void textPeriodeDate_EditValueChanged_1(object sender, EventArgs e)
        {
            if (textPeriodeDate.EditValue.ToString() == "All")
            {
                gridViewUnit.ActiveFilterString = null;
            }
            else if (textPeriodeDate.EditValue.ToString() == "To Day")
            {
                gridViewUnit.ActiveFilterString = string.Format("IsOutlookIntervalToday([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "This Week")
            {
                gridViewUnit.ActiveFilterString = string.Format("IsThisWeek([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "Last Week")
            {
                gridViewUnit.ActiveFilterString = string.Format("IsOutlookIntervalLastWeek([created_at])");
            }
            else if (textPeriodeDate.EditValue.ToString() == "Newest")
            {
                gridViewUnit.Columns["id"].SortOrder = ColumnSortOrder.Ascending;
            }
            else if (textPeriodeDate.EditValue.ToString() == "Oldest")
            {
                gridViewUnit.Columns["id"].SortOrder = ColumnSortOrder.Descending;
            }
            else if (textPeriodeDate.EditValue.ToString() == "Between the dates")
            {
                startDate.Enabled = true;
                endDate.Enabled = true;
                gridViewUnit.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
            }
        }

        private void btnReset_Click_1(object sender, EventArgs e)
        {
            this.filter = false;
            gridViewUnit.ClearSorting();
            gridViewUnit.ApplyFindFilter(string.Empty);
            textPeriodeDate.EditValue = "";
            startDate.Text = DateTime.Now.ToString();
            endDate.Text = DateTime.Now.ToString();

            if (Properties.Settings.Default.sound == "yes")
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Wrong.wav");
                simpleSound.Play();
            }
        }

        private void startDate_EditValueChanged_1(object sender, EventArgs e)
        {
            if ( endDate.EditValue != null & this.filter )
                gridViewUnit.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
        }

        private void endDate_EditValueChanged_1(object sender, EventArgs e)
        {
            if ( startDate.EditValue != null & this.filter )
                gridViewUnit.ActiveFilterString = string.Format("[created_at] Between(#" + startDate.DateTime + "#, #" + endDate.DateTime + "#)");
        }
    }
}