using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Restaurant.Zone
{
    public partial class Form_Edit_Zone : DevExpress.XtraEditors.XtraForm
    {
        BL.Zone.Zone zone = new BL.Zone.Zone();
        Form_Zones form_zones = null;
        int zone_id = 0;

        public Form_Edit_Zone()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceZone.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = zone.get_zone(this.zone_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
            }
        }

        public void setObject(Form_Zones form_zones)
        {
            this.form_zones = form_zones;
        }

        public void setID(int zone_id)
        {
            this.zone_id = zone_id;
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                zone.update_zone(this.zone_id, txtName.Text, txtName.Text, DateTime.Now);
                txtName.Select();
                sqlDataSourceZone.FillAsync();

                if (this.form_zones != null)
                    this.form_zones.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Unit_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}