using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Restaurant.Table
{
    public partial class Form_Add_Table : DevExpress.XtraEditors.XtraForm
    {
        BL.Table.Table table = new BL.Table.Table();
        Form_Table_List form_table_list = null;

        public Form_Add_Table()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceTable.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceBranch.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceZone.FillAsync();
        }

        public void setObject(Form_Table_List form_table_list)
        {
            this.form_table_list = form_table_list;
        }

        private void btnAdd_Click_1(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                table.add_table(txtName.Text, txtName.Text, txtCapacity.Text, "assigned_to_section", 1, 1, DateTime.Now, 1, 1, "status", DateTime.Now, DateTime.Now);
                txtName.Clear();
                txtName.Select();
                sqlDataSourceTable.FillAsync();

                if (this.form_table_list != null)
                    this.form_table_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }
    }
}