using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Restaurant.Table
{
    public partial class Form_Edit_Table : DevExpress.XtraEditors.XtraForm
    {
        BL.Table.Table table = new BL.Table.Table();
        Form_Table_List form_table_list = null;
        int table_id = 0;

        public Form_Edit_Table()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceTable.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceBranch.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceZone.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = table.get_table(this.table_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
                txtCapacity.Text = tb.Rows[0]["capacity"].ToString();
                txtBranch.EditValue = tb.Rows[0]["branch_id"];
                area.EditValue = tb.Rows[0]["zone_id"];
            }
        }
        

        public void setObject(Form_Table_List form_table_list)
        {
            this.form_table_list = form_table_list;
        }

        public void setID(int table_id)
        {
            this.table_id = table_id;
        }

        private void btnAdd_Click_1(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                //Convert.ToInt32(txtBranch.EditValue.ToString())
                table.update_table(this.table_id, txtName.Text, txtName.Text, txtCapacity.Text, "assigned_to_section", 1, 1, DateTime.Now, 1, 1, "status", DateTime.Now);
                txtName.Select();
                sqlDataSourceTable.FillAsync();

                if (this.form_table_list != null)
                    this.form_table_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Table_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}