using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Stock.Supplier
{
    public partial class Form_Edit_Supplier : DevExpress.XtraEditors.XtraForm
    {
        BL.Supplier.Supplier supplier = new BL.Supplier.Supplier();
        Form_Supplier_List form_supplier_list = null;
        int supplier_id = 0;

        public Form_Edit_Supplier()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceSupplier.FillAsync();
        }

        public void loadData()
        {
            DataTable tb = supplier.get_supplier(this.supplier_id);
            if (tb.Rows.Count > 0)
            {
                txtName.Text = tb.Rows[0]["name"].ToString();
                txtEmail.Text = tb.Rows[0]["email"].ToString();
                txtPhone.Text = tb.Rows[0]["phn_no"].ToString();
                txtAddress.Text = tb.Rows[0]["address"].ToString();
            }
        }

        public void setObject(Form_Supplier_List form_supplier_list)
        {
            this.form_supplier_list = form_supplier_list;
        }

        public void setID(int supplier_id)
        {
            this.supplier_id = supplier_id;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                supplier.update_supplier(this.supplier_id, txtName.Text, txtName.Text, txtEmail.Text, txtPhone.Text, 0, txtAddress.Text, DateTime.Now);
                txtName.Select();

                sqlDataSourceSupplier.FillAsync();

                if (this.form_supplier_list != null)
                    this.form_supplier_list.asyncData();

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {
                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void Form_Edit_Supplier_Load(object sender, EventArgs e)
        {
            loadData();
        }
    }
}