using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ezziresto.PL.Customer
{
    public partial class Form_Custommer : DevExpress.XtraEditors.XtraForm
    {
        BL.Customer.Customer customer = new BL.Customer.Customer();
        DataTable tb, customers = new DataTable();
        Form_Customers form_customers;
        int customer_id = 0;
        int max_id = 0;
        int row = 0;

        public Form_Custommer()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceCustommer.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSourceBranch.FillAsync();
        }

        public void setObject(Form_Customers form_customers)
        {
            this.form_customers = form_customers;
        }

        public void setID(int customer_id)
        {
            this.customer_id = customer_id;
            this.row = customer_id;
        }

        public void last_id()
        {
            txtID.Text = (Convert.ToInt32(customer.get_last_id()) + 1).ToString();
            this.max_id = Convert.ToInt32(customer.get_last_id());
            if (customer.get_last_id() == "")
            {
                txtID.Text = "1";
            } else { 
                txtID.Text = (Convert.ToInt32(customer.get_last_id()) + 1).ToString();
            }

            txtName.Clear();
            txtNotes.Clear();
            txtPhone.Clear();
            memoAdress.Clear();

            btnAdd.Enabled = true;
            btnRefresh.Enabled = true;
            btnDelete.Enabled = false;
            btnDeleteAll.Enabled = false;
            btnSave.Enabled = false;
        }

        public void load()
        {
            if (this.customers.Rows.Count <= row)
            {
                MessageBox.Show("Aucune donnée sur cet écran");
            }
            else
            {
                txtID.Text = this.customers.Rows[row]["id"].ToString();
                txtName.Text = this.customers.Rows[row]["name"].ToString();
                memoAdress.Text = this.customers.Rows[row]["address"].ToString();
                txtPhone.Text = this.customers.Rows[row]["phn_no"].ToString();
                txtBranch.EditValue = this.customers.Rows[row]["branch_id"];
                txtEmail.Text = this.customers.Rows[row]["email"].ToString();

                btnAdd.Enabled = false;
                btnRefresh.Enabled = true;
                btnDelete.Enabled = true;
                btnDeleteAll.Enabled = true;
                btnSave.Enabled = true;
            }
        }

        public void Get(int id)
        {
            DataTable tb = customer.get_customer(id);

            if (tb.Rows.Count <= 0)
            {
                MessageBox.Show("Aucune donnée sur cet écran");
            }
            else
            {
                txtID.Text = tb.Rows[0]["id"].ToString();
                txtName.Text = tb.Rows[0]["name"].ToString();
                memoAdress.Text = tb.Rows[0]["address"].ToString();
                txtPhone.Text = tb.Rows[0]["phn_no"].ToString();
                txtBranch.EditValue = tb.Rows[0]["branch_id"];
                txtEmail.Text = tb.Rows[0]["email"].ToString();

                btnAdd.Enabled = false;
                btnRefresh.Enabled = true;
                btnDelete.Enabled = true;
                btnDeleteAll.Enabled = true;
                btnSave.Enabled = true;
            }
        }

        private void textEdit5_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton7_Click(object sender, EventArgs e)
        {

        }

        private void textEdit5_EditValueChanged_1(object sender, EventArgs e)
        {

        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            last_id();
        }

        private void txtPohne_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                customer.add_customer(txtName.Text, txtPhone.Text, txtName.Text, txtEmail.Text, txtType.EditValue.ToString(),memoAdress.Text, Convert.ToInt32(txtBranch.EditValue), DateTime.Now, DateTime.Now);
                
                this.last_id();

                if (this.form_customers != null)
                    this.form_customers.asyncData();


                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                customer.update_customer(Convert.ToInt32(txtID.Text), txtName.Text, txtPhone.Text, txtName.Text, txtEmail.Text, txtType.EditValue.ToString(), memoAdress.Text, Convert.ToInt32(txtBranch.EditValue), DateTime.Now);

                if (this.form_customers != null)
                    this.form_customers.asyncData();


                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                    simpleSound.Play();
                }
            }
            else
            {

                if (Properties.Settings.Default.sound == "yes")
                {
                    SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                    simpleSound.Play();
                }
            }
        }

        private void btnDeleteAll_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("êtes-vous sûr ?", "Confirmer", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                customer.delete_all();
                this.last_id();
            }
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("êtes-vous sûr ?", "Confirmer", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                customer.delete(Convert.ToInt32(txtID.Text));
                this.last_id();
            }
        }

        private void btnRight2_Click(object sender, EventArgs e)
        {
            row = Convert.ToInt32(customer.get_last_id()) - 1;
            load();
            btnRight.Enabled = false;
            btnLeft.Enabled = true;
        }

        private void btnRight_Click(object sender, EventArgs e)
        {
            if ((Convert.ToInt32(customer.get_last_id())) > row)
            {
                row++;
                load();
                btnLeft.Enabled = true;
            }
            else
            {
                btnRight.Enabled = false;
            }
        }

        private void btnLeft2_Click(object sender, EventArgs e)
        {
            row = 0;
            load();
            btnLeft.Enabled = false;
            btnRight.Enabled = true;
        }

        private void btnLeft_Click(object sender, EventArgs e)
        {
            if (row > 0)
            {
                row--;
                load();
                btnRight.Enabled = true;
            }
            else
            {
                btnLeft.Enabled = false;
            }
        }

        private void searchLookUpClient_EditValueChanged(object sender, EventArgs e)
        {
            object obj = searchLookUpCustommer.EditValue;
            //string text = searchLookUpClient.Text;
            //MessageBox.Show(obj.ToString());
            Get(Convert.ToInt32(obj));
        }

        private void searchLookUpClient_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
        }

        private void searchLookUpClient_ButtonPressed(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            MessageBox.Show(e.ToString());
        }

        private void btnExit_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void Form_Custommer_Load(object sender, EventArgs e)
        {
            this.customers = customer.get_all_customers();

            if (this.customer_id != 0)
            {
                txtID.Text = this.customer_id.ToString();
                this.Get(this.customer_id);
            }
            else
            {
                last_id();

                if (customer.get_last_id() == "")
                {
                    txtID.Text = "1";
                    btnRight.Enabled = false;
                    btnRight2.Enabled = false;
                    btnLeft.Enabled = false;
                    btnLeft2.Enabled = false;
                }
                else
                {
                    this.row = Convert.ToInt32(customer.get_last_id());
                }
            }
        }
    }
}